# Searching Arrays


In [3]:
# we can search an array for a certain value and return the indexes that get a match.To search an array use the where() method
# Example 1-->>
import numpy as np
arr = np.array([1,2,3,4,5,6,4])
x = np.where(arr==4)
print(x)

(array([3, 6], dtype=int64),)


In [4]:
# Example 2-->>
import numpy as np
arr = np.array([[1,2,3,4,5,6,7]])
x = np.where(arr%2==0)
print(x)

(array([0, 0, 0], dtype=int64), array([1, 3, 5], dtype=int64))


In [5]:
# Example 3-->>
import numpy as np
arr = np.array([[1,2,3,4,5,6,7]])
x = np.where(arr%2==1)
print(x)

(array([0, 0, 0, 0], dtype=int64), array([0, 2, 4, 6], dtype=int64))


# Search Sorted

In [6]:
# There is a method called searchsorted() which performs a binary search in the array and returns the index where the specified
# value where the specified value would be inserted to maintain the search order. The searchsorted() method is assumed to be
# used on sorted arrays.
# Example -->>
import numpy as np 
arr = np.array([6,7,8,9])
x = np.searchsorted(arr,7)
print(x)

1


In [7]:
# Example-->>
import numpy as np
arr = np.array([6,7,8,9])
x = np.searchsorted(arr,7, side='right')
print(x)

2


In [8]:
# Example-->>
import numpy as np
arr = np.array([1,3,5,7])
x = np.searchsorted(arr,[2,4,6])
print(x)

[1 2 3]


# Numpy Filter Array 

In [10]:
# Getting some elements out of an existing array and creating a new array out of them is called filtering
# Example-->>
import numpy as np
arr = np.array([1,2,4,6])
x = [True,False,True,False]
new_arr = arr[x]
print(new_arr)

[1 4]


In [11]:
# Example-->>
import numpy as np
arr = np.array([41,42,43,45])
filter_arr = [] #empty list
for x in arr:
    if x > 42:
        filter_arr.append(True)
    else :
        filter_arr.append(False)
new_arr = arr[filter_arr]
print(filter_arr)
print(new_arr)
        


[False, False, True, True]
[43 45]


In [12]:
# Example-->>
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
filter_arr = [] #empty list
for x in arr:
    if x %2==0:
        filter_arr.append(True)
    else :
        filter_arr.append(False)
new_arr = arr[filter_arr]
print(filter_arr)
print(new_arr)
        


[False, True, False, True, False, True, False]
[2 4 6]


In [13]:
# Example-->>
import numpy as np
arr = np.array([41,42,43,45])
filter_arr = arr> 42
new_arr = arr[filter_arr]
print(filter_arr)
print(new_arr)

[False False  True  True]
[43 45]


In [14]:
# Example-->>
import numpy as np
arr = np.array([41,42,43,45])
filter_arr = arr%2 ==0
new_arr = arr[filter_arr]
print(filter_arr)
print(new_arr)

[False  True False False]
[42]
